name: Docker Image CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx run validate
  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build, and push image
        run: |
          docker login --username bilal-a-g --password ${{secrets.GH_TOKEN}} ghcr.io
          docker build . --tag ghcr.io/bilal-a-g/catan-frontend:latest
          docker push ghcr.io/bilal-a-g/catan-frontend:latest